//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/MyInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerActionMap"",
            ""id"": ""d099c7c1-ea87-4550-9e80-c53138cd89d5"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""373db96e-e50a-4acf-a8f5-a14258435d4d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""39ef02ad-18f2-49c2-90fd-5a9879c90813"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""a509d710-ccdc-45f5-837b-43dec48148c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""f031087b-8f33-4607-a098-5cdf8398d9ba"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AimAndFire"",
                    ""type"": ""Button"",
                    ""id"": ""e6ed358f-97e0-4f2c-a946-9fe141c9c6f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire1"",
                    ""type"": ""Button"",
                    ""id"": ""c667d183-2907-45a0-9754-66b26db82510"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire2"",
                    ""type"": ""Button"",
                    ""id"": ""8ffa76bc-9cda-4197-9ca5-1bf915d7c3be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""66df0c93-bc63-432c-8219-afe9b2a7c72e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Numkeys"",
                    ""type"": ""Button"",
                    ""id"": ""a2e5de15-6227-497b-9bdc-60c8d1da3a49"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""7a2a6740-1695-4795-a10d-ba0b93ca6924"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""96ae4081-3e3b-4db2-9b5b-61ee30cdd927"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateRight"",
                    ""type"": ""Button"",
                    ""id"": ""38898324-4b73-40f1-8e9b-df1608c9a63f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e888f498-c5a4-4854-93d9-b3f067c2db09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""8db403d5-3a7f-475d-a0c6-21a42cfc68da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCloseCraftingMenu"",
                    ""type"": ""Button"",
                    ""id"": ""f6f2530b-2384-4718-af6c-0e72194739bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCloseEquipmentAndFood"",
                    ""type"": ""Button"",
                    ""id"": ""0d806854-2503-4036-8956-ec79aa21a07a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Craft"",
                    ""type"": ""Button"",
                    ""id"": ""81614165-a9e1-469c-8838-51bbade522c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmPlacement"",
                    ""type"": ""Button"",
                    ""id"": ""815144f3-959b-49b9-bc07-a504eee5dc52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelPlacement"",
                    ""type"": ""Button"",
                    ""id"": ""0e439683-dd7b-4fd6-90e1-1299c800f171"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowHideDebugTools"",
                    ""type"": ""Button"",
                    ""id"": ""255870e8-0348-4f32-bac1-257f8eb2fc27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReportBug"",
                    ""type"": ""Button"",
                    ""id"": ""3c79c4cf-40c8-46af-911c-9a247d9c07e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4e081fc9-7998-47f9-a9a3-27b82d46c5a7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86f0c563-e2af-46fe-bf34-66ee9d7983fb"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD Keys"",
                    ""id"": ""c3613426-79d4-40f0-bb68-7db602a95985"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fa82c79a-4ee9-4df6-9f84-8bc18f5d820c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c70c1ac3-1dbf-4794-89b1-3473d35b064f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6388373c-4593-4f46-83b0-899dc51378c9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""52bca673-7fdd-49ae-8731-92d4f9f7acaf"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""57ab3f83-0283-4835-8d47-0610b88cbbaa"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2193d126-d92d-4805-812e-854a0e457c9b"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7231dbb-f1c9-469e-95bb-f20b88296ff1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75c31fea-8202-4d1b-b3cc-788318ea2d0b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65097cdd-4896-4d36-b67d-590df3dd8faf"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b69dd57b-4616-4746-b980-471abbc03106"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1d71e35-8c03-4765-8fb1-178da280db39"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f72c065-15d3-4767-96c6-7cf5e7c6d1c8"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f211d44-8250-4cac-b231-e4b2cbcea18f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""515e78df-7d64-4cb0-a9e9-a31ea6365042"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e068efa6-1ee9-4696-8306-83e2438aa463"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0824cb4-9ac3-4d14-bf10-951d9cf6be06"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51d92cfb-2ec7-439c-8be5-8fc1b362ce54"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a789287b-e21f-4cd2-ba1a-3f50f27b3c73"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd21dd7c-30f9-421f-ac93-efe145be230c"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7c6dbb5-984d-4bb7-a6f5-c8ed7e4976b7"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7569c7b-1ba7-4a19-9233-fd8ad931c9d4"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed0a946d-6d16-44ab-b70b-2c2637a9f4b5"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Numkeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8063b5a7-35d8-44b2-9bb6-2619b964ce7c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7373b820-a8dd-4ac2-9248-d11b50556174"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a5ddb08-554e-4178-9220-6c61796de809"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfd3d9a2-cf8c-4f68-990f-37be289d30ad"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60e2f745-cb4e-4b2e-86e3-51e95740d41b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9243e79f-880b-48e9-9113-4f9de120744f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0304b8ca-3de2-4677-86a1-7ac96913c50a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Craft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28d1b447-3186-43e3-9936-64f95b61b8b5"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""OpenCloseCraftingMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39bccbf6-b05a-4dd5-ba62-2b21b70311c3"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""OpenCloseCraftingMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f612f2d-aec1-4393-9eb6-45b01616ebfd"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AimAndFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab085b6f-dcb6-4c02-b8f1-ed439ecf17e9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ConfirmPlacement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b089528e-719a-433a-a6d5-d802affa2b70"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ConfirmPlacement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30bd303c-dcdb-4949-9561-c5409f3454fd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""CancelPlacement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d4b9750-46a1-4e17-b29e-ea0d58149e7d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CancelPlacement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5eaeea67-bd0b-47c3-8ce6-e78accdb31ca"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""OpenCloseEquipmentAndFood"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a508676b-b9fa-4211-aefd-c8077bed19fa"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""OpenCloseEquipmentAndFood"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64bf86a2-0528-4fc9-b21f-9d53376e8ceb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Fire2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2548c515-220b-4541-ac9a-4571ae24aa0e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavigateArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ca3fb96-50c7-4d96-83cc-aa52b1052a75"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a63b4dca-ee28-49f7-9b83-5d68864a751e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavigateArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2ec4b6b-2370-49bd-9405-fa2e254ddc73"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33505e48-90a6-4f3a-bf38-ba22a72e095d"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowHideDebugTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23fcd648-faca-45ec-9ab0-6f1dae1e2f5d"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReportBug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UserIntefaceActionMap"",
            ""id"": ""82509205-eeef-40b6-b1ef-f70990d2d56c"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e2d8894e-f80e-4a96-abcb-0cb3404d000a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""9dd69811-4230-4cf5-81bc-2c9b7ad11280"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Purge"",
                    ""type"": ""Button"",
                    ""id"": ""03158307-1194-4b30-a15b-af3b640413e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reroll"",
                    ""type"": ""Button"",
                    ""id"": ""5c1fa06c-0edb-49fe-a19a-bfa6f9779efa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""92d64528-8c64-4e1d-b6c0-c0c7ae925c61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""362465c5-8917-4482-a3b7-22920fc097cc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""19992fac-949d-4c10-9040-43ec3e13d6fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ea9d34b8-dce5-4c6d-88bc-a3831a46e0fe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2d987681-c6ac-4d01-80b2-2b6a7d023250"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""3f2967d2-5a9b-46a6-9c67-c3d070d4b72b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""2b80e7c4-fbd7-47d6-ace4-758a33db2c44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b192c92a-5dcd-462d-b1ea-e18847cf51af"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b11b09ee-c9d5-4d43-929b-7d36e56f7b8a"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""7a4c4373-93d3-4d1a-9ad8-bc4b4576cf43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Console"",
                    ""type"": ""Button"",
                    ""id"": ""ed6abd01-fbf1-4b07-896e-9577f0828f3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2df4714e-0840-4014-9dd5-b65e6ebe8cf8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19d2a150-bf0c-455e-91c6-d1787e3bfced"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e744389-4331-40ca-8705-9d4a4267b48c"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3c4a508-a822-4b10-b92e-25ed492408ea"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""374e4cb2-8b27-4b3e-bbb2-2f4f43f757df"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd11e115-d396-4680-b331-9267aa34bfe9"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4823ac39-0d31-45c7-a2c4-b5f570813725"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c924375-79b6-4800-acc3-1b2596d789b1"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""460cb2d0-f9aa-4413-9d18-88de917a8440"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6647777f-8a6a-4e39-b434-3f56fe629910"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fefbf73e-658e-4209-a1dd-679e8207616c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4350efc-e4f1-425f-a580-a1f645cb70be"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0031639f-fccb-4156-a9f3-aa3ed55ef82f"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""7933296e-143a-4990-b25e-4d811628a603"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cf614516-515c-40dd-8bdc-8108c1687497"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0d57fedc-c93f-41d5-80f7-e4cd979606d0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fab392a5-1ea5-45f2-89d3-5eae73aca094"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""876d1093-671b-4c85-941f-fa7899aa308b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""34d09644-ae96-40c3-96c8-a5f2a13c64f3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e0def7e1-42c7-4b6c-9d82-b5de477a8259"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2c635e32-18df-451c-aa53-c0af9db5fa15"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""31267c61-7ce7-4925-a712-4d2b1e4fb69a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""a2bd7871-fddb-4eab-9f68-9b88479aa112"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9b25df58-6303-4ccc-9535-84a646e49b2b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ab9e8f35-2ad8-4270-a1ec-b6e95858e886"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""414d852c-ce84-4a33-84f4-d156e53ef38b"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7e04d538-3432-4cf7-8a31-649eff571680"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""17c9735c-14e1-447e-a878-34a453af7b0e"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5d7ab090-cf2e-4a0f-9477-c215c137de3e"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f1a308ad-4c48-42b8-89b4-5064d3027313"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3a7edbc2-722b-40b0-afd3-760d820be91d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a4f9ac34-3345-4040-af47-28bf7ccd5044"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cac8a76a-9ae3-404e-b682-32a58ffe7744"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12deb0f8-b566-42d8-98bb-8974e3400a75"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Console"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23f92a63-844a-4f5f-89db-39586c87f92c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Keyboard&Mouse"",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62668ec8-0d6d-4c4b-820a-387bfe1f4227"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Purge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc20d694-25d3-4716-bad7-05c264cb69e1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Purge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0145793d-4f88-4fac-a5e3-4c9360370af2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Reroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d38a8651-0490-43f5-99f6-48296eba9b00"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Reroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CraftingBookActionMap"",
            ""id"": ""918f2edf-b063-4b54-aa5a-c889c8b56a27"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d84a03b8-f9fa-4901-b747-b759b38a8640"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""e8214723-3ce8-4338-8af8-c8fab8e7fccd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""770d0c86-bb5a-4d9c-a527-1cca39f6c0d2"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8dfab2db-5885-4159-82ad-5adb8ac058ab"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0191a7ac-dd63-4bdb-bbed-2b351a4d8e2b"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""18c784aa-91f9-4edb-bcb0-fa9bca132a4d"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerActionMap
        m_PlayerActionMap = asset.FindActionMap("PlayerActionMap", throwIfNotFound: true);
        m_PlayerActionMap_Movement = m_PlayerActionMap.FindAction("Movement", throwIfNotFound: true);
        m_PlayerActionMap_Interact = m_PlayerActionMap.FindAction("Interact", throwIfNotFound: true);
        m_PlayerActionMap_Dash = m_PlayerActionMap.FindAction("Dash", throwIfNotFound: true);
        m_PlayerActionMap_Aim = m_PlayerActionMap.FindAction("Aim", throwIfNotFound: true);
        m_PlayerActionMap_AimAndFire = m_PlayerActionMap.FindAction("AimAndFire", throwIfNotFound: true);
        m_PlayerActionMap_Fire1 = m_PlayerActionMap.FindAction("Fire1", throwIfNotFound: true);
        m_PlayerActionMap_Fire2 = m_PlayerActionMap.FindAction("Fire2", throwIfNotFound: true);
        m_PlayerActionMap_Drop = m_PlayerActionMap.FindAction("Drop", throwIfNotFound: true);
        m_PlayerActionMap_Numkeys = m_PlayerActionMap.FindAction("Numkeys", throwIfNotFound: true);
        m_PlayerActionMap_Pause = m_PlayerActionMap.FindAction("Pause", throwIfNotFound: true);
        m_PlayerActionMap_NavigateLeft = m_PlayerActionMap.FindAction("NavigateLeft", throwIfNotFound: true);
        m_PlayerActionMap_NavigateRight = m_PlayerActionMap.FindAction("NavigateRight", throwIfNotFound: true);
        m_PlayerActionMap_NavigateArrowLeft = m_PlayerActionMap.FindAction("NavigateArrowLeft", throwIfNotFound: true);
        m_PlayerActionMap_NavigateArrowRight = m_PlayerActionMap.FindAction("NavigateArrowRight", throwIfNotFound: true);
        m_PlayerActionMap_OpenCloseCraftingMenu = m_PlayerActionMap.FindAction("OpenCloseCraftingMenu", throwIfNotFound: true);
        m_PlayerActionMap_OpenCloseEquipmentAndFood = m_PlayerActionMap.FindAction("OpenCloseEquipmentAndFood", throwIfNotFound: true);
        m_PlayerActionMap_Craft = m_PlayerActionMap.FindAction("Craft", throwIfNotFound: true);
        m_PlayerActionMap_ConfirmPlacement = m_PlayerActionMap.FindAction("ConfirmPlacement", throwIfNotFound: true);
        m_PlayerActionMap_CancelPlacement = m_PlayerActionMap.FindAction("CancelPlacement", throwIfNotFound: true);
        m_PlayerActionMap_ShowHideDebugTools = m_PlayerActionMap.FindAction("ShowHideDebugTools", throwIfNotFound: true);
        m_PlayerActionMap_ReportBug = m_PlayerActionMap.FindAction("ReportBug", throwIfNotFound: true);
        // UserIntefaceActionMap
        m_UserIntefaceActionMap = asset.FindActionMap("UserIntefaceActionMap", throwIfNotFound: true);
        m_UserIntefaceActionMap_Navigate = m_UserIntefaceActionMap.FindAction("Navigate", throwIfNotFound: true);
        m_UserIntefaceActionMap_Submit = m_UserIntefaceActionMap.FindAction("Submit", throwIfNotFound: true);
        m_UserIntefaceActionMap_Purge = m_UserIntefaceActionMap.FindAction("Purge", throwIfNotFound: true);
        m_UserIntefaceActionMap_Reroll = m_UserIntefaceActionMap.FindAction("Reroll", throwIfNotFound: true);
        m_UserIntefaceActionMap_Cancel = m_UserIntefaceActionMap.FindAction("Cancel", throwIfNotFound: true);
        m_UserIntefaceActionMap_Point = m_UserIntefaceActionMap.FindAction("Point", throwIfNotFound: true);
        m_UserIntefaceActionMap_Click = m_UserIntefaceActionMap.FindAction("Click", throwIfNotFound: true);
        m_UserIntefaceActionMap_ScrollWheel = m_UserIntefaceActionMap.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UserIntefaceActionMap_MiddleClick = m_UserIntefaceActionMap.FindAction("MiddleClick", throwIfNotFound: true);
        m_UserIntefaceActionMap_RightClick = m_UserIntefaceActionMap.FindAction("RightClick", throwIfNotFound: true);
        m_UserIntefaceActionMap_Esc = m_UserIntefaceActionMap.FindAction("Esc", throwIfNotFound: true);
        m_UserIntefaceActionMap_TrackedDevicePosition = m_UserIntefaceActionMap.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_UserIntefaceActionMap_TrackedDeviceOrientation = m_UserIntefaceActionMap.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
        m_UserIntefaceActionMap_Start = m_UserIntefaceActionMap.FindAction("Start", throwIfNotFound: true);
        m_UserIntefaceActionMap_Console = m_UserIntefaceActionMap.FindAction("Console", throwIfNotFound: true);
        // CraftingBookActionMap
        m_CraftingBookActionMap = asset.FindActionMap("CraftingBookActionMap", throwIfNotFound: true);
        m_CraftingBookActionMap_Navigate = m_CraftingBookActionMap.FindAction("Navigate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActionMap
    private readonly InputActionMap m_PlayerActionMap;
    private List<IPlayerActionMapActions> m_PlayerActionMapActionsCallbackInterfaces = new List<IPlayerActionMapActions>();
    private readonly InputAction m_PlayerActionMap_Movement;
    private readonly InputAction m_PlayerActionMap_Interact;
    private readonly InputAction m_PlayerActionMap_Dash;
    private readonly InputAction m_PlayerActionMap_Aim;
    private readonly InputAction m_PlayerActionMap_AimAndFire;
    private readonly InputAction m_PlayerActionMap_Fire1;
    private readonly InputAction m_PlayerActionMap_Fire2;
    private readonly InputAction m_PlayerActionMap_Drop;
    private readonly InputAction m_PlayerActionMap_Numkeys;
    private readonly InputAction m_PlayerActionMap_Pause;
    private readonly InputAction m_PlayerActionMap_NavigateLeft;
    private readonly InputAction m_PlayerActionMap_NavigateRight;
    private readonly InputAction m_PlayerActionMap_NavigateArrowLeft;
    private readonly InputAction m_PlayerActionMap_NavigateArrowRight;
    private readonly InputAction m_PlayerActionMap_OpenCloseCraftingMenu;
    private readonly InputAction m_PlayerActionMap_OpenCloseEquipmentAndFood;
    private readonly InputAction m_PlayerActionMap_Craft;
    private readonly InputAction m_PlayerActionMap_ConfirmPlacement;
    private readonly InputAction m_PlayerActionMap_CancelPlacement;
    private readonly InputAction m_PlayerActionMap_ShowHideDebugTools;
    private readonly InputAction m_PlayerActionMap_ReportBug;
    public struct PlayerActionMapActions
    {
        private @MyInputActions m_Wrapper;
        public PlayerActionMapActions(@MyInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerActionMap_Movement;
        public InputAction @Interact => m_Wrapper.m_PlayerActionMap_Interact;
        public InputAction @Dash => m_Wrapper.m_PlayerActionMap_Dash;
        public InputAction @Aim => m_Wrapper.m_PlayerActionMap_Aim;
        public InputAction @AimAndFire => m_Wrapper.m_PlayerActionMap_AimAndFire;
        public InputAction @Fire1 => m_Wrapper.m_PlayerActionMap_Fire1;
        public InputAction @Fire2 => m_Wrapper.m_PlayerActionMap_Fire2;
        public InputAction @Drop => m_Wrapper.m_PlayerActionMap_Drop;
        public InputAction @Numkeys => m_Wrapper.m_PlayerActionMap_Numkeys;
        public InputAction @Pause => m_Wrapper.m_PlayerActionMap_Pause;
        public InputAction @NavigateLeft => m_Wrapper.m_PlayerActionMap_NavigateLeft;
        public InputAction @NavigateRight => m_Wrapper.m_PlayerActionMap_NavigateRight;
        public InputAction @NavigateArrowLeft => m_Wrapper.m_PlayerActionMap_NavigateArrowLeft;
        public InputAction @NavigateArrowRight => m_Wrapper.m_PlayerActionMap_NavigateArrowRight;
        public InputAction @OpenCloseCraftingMenu => m_Wrapper.m_PlayerActionMap_OpenCloseCraftingMenu;
        public InputAction @OpenCloseEquipmentAndFood => m_Wrapper.m_PlayerActionMap_OpenCloseEquipmentAndFood;
        public InputAction @Craft => m_Wrapper.m_PlayerActionMap_Craft;
        public InputAction @ConfirmPlacement => m_Wrapper.m_PlayerActionMap_ConfirmPlacement;
        public InputAction @CancelPlacement => m_Wrapper.m_PlayerActionMap_CancelPlacement;
        public InputAction @ShowHideDebugTools => m_Wrapper.m_PlayerActionMap_ShowHideDebugTools;
        public InputAction @ReportBug => m_Wrapper.m_PlayerActionMap_ReportBug;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionMapActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @AimAndFire.started += instance.OnAimAndFire;
            @AimAndFire.performed += instance.OnAimAndFire;
            @AimAndFire.canceled += instance.OnAimAndFire;
            @Fire1.started += instance.OnFire1;
            @Fire1.performed += instance.OnFire1;
            @Fire1.canceled += instance.OnFire1;
            @Fire2.started += instance.OnFire2;
            @Fire2.performed += instance.OnFire2;
            @Fire2.canceled += instance.OnFire2;
            @Drop.started += instance.OnDrop;
            @Drop.performed += instance.OnDrop;
            @Drop.canceled += instance.OnDrop;
            @Numkeys.started += instance.OnNumkeys;
            @Numkeys.performed += instance.OnNumkeys;
            @Numkeys.canceled += instance.OnNumkeys;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @NavigateLeft.started += instance.OnNavigateLeft;
            @NavigateLeft.performed += instance.OnNavigateLeft;
            @NavigateLeft.canceled += instance.OnNavigateLeft;
            @NavigateRight.started += instance.OnNavigateRight;
            @NavigateRight.performed += instance.OnNavigateRight;
            @NavigateRight.canceled += instance.OnNavigateRight;
            @NavigateArrowLeft.started += instance.OnNavigateArrowLeft;
            @NavigateArrowLeft.performed += instance.OnNavigateArrowLeft;
            @NavigateArrowLeft.canceled += instance.OnNavigateArrowLeft;
            @NavigateArrowRight.started += instance.OnNavigateArrowRight;
            @NavigateArrowRight.performed += instance.OnNavigateArrowRight;
            @NavigateArrowRight.canceled += instance.OnNavigateArrowRight;
            @OpenCloseCraftingMenu.started += instance.OnOpenCloseCraftingMenu;
            @OpenCloseCraftingMenu.performed += instance.OnOpenCloseCraftingMenu;
            @OpenCloseCraftingMenu.canceled += instance.OnOpenCloseCraftingMenu;
            @OpenCloseEquipmentAndFood.started += instance.OnOpenCloseEquipmentAndFood;
            @OpenCloseEquipmentAndFood.performed += instance.OnOpenCloseEquipmentAndFood;
            @OpenCloseEquipmentAndFood.canceled += instance.OnOpenCloseEquipmentAndFood;
            @Craft.started += instance.OnCraft;
            @Craft.performed += instance.OnCraft;
            @Craft.canceled += instance.OnCraft;
            @ConfirmPlacement.started += instance.OnConfirmPlacement;
            @ConfirmPlacement.performed += instance.OnConfirmPlacement;
            @ConfirmPlacement.canceled += instance.OnConfirmPlacement;
            @CancelPlacement.started += instance.OnCancelPlacement;
            @CancelPlacement.performed += instance.OnCancelPlacement;
            @CancelPlacement.canceled += instance.OnCancelPlacement;
            @ShowHideDebugTools.started += instance.OnShowHideDebugTools;
            @ShowHideDebugTools.performed += instance.OnShowHideDebugTools;
            @ShowHideDebugTools.canceled += instance.OnShowHideDebugTools;
            @ReportBug.started += instance.OnReportBug;
            @ReportBug.performed += instance.OnReportBug;
            @ReportBug.canceled += instance.OnReportBug;
        }

        private void UnregisterCallbacks(IPlayerActionMapActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @AimAndFire.started -= instance.OnAimAndFire;
            @AimAndFire.performed -= instance.OnAimAndFire;
            @AimAndFire.canceled -= instance.OnAimAndFire;
            @Fire1.started -= instance.OnFire1;
            @Fire1.performed -= instance.OnFire1;
            @Fire1.canceled -= instance.OnFire1;
            @Fire2.started -= instance.OnFire2;
            @Fire2.performed -= instance.OnFire2;
            @Fire2.canceled -= instance.OnFire2;
            @Drop.started -= instance.OnDrop;
            @Drop.performed -= instance.OnDrop;
            @Drop.canceled -= instance.OnDrop;
            @Numkeys.started -= instance.OnNumkeys;
            @Numkeys.performed -= instance.OnNumkeys;
            @Numkeys.canceled -= instance.OnNumkeys;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @NavigateLeft.started -= instance.OnNavigateLeft;
            @NavigateLeft.performed -= instance.OnNavigateLeft;
            @NavigateLeft.canceled -= instance.OnNavigateLeft;
            @NavigateRight.started -= instance.OnNavigateRight;
            @NavigateRight.performed -= instance.OnNavigateRight;
            @NavigateRight.canceled -= instance.OnNavigateRight;
            @NavigateArrowLeft.started -= instance.OnNavigateArrowLeft;
            @NavigateArrowLeft.performed -= instance.OnNavigateArrowLeft;
            @NavigateArrowLeft.canceled -= instance.OnNavigateArrowLeft;
            @NavigateArrowRight.started -= instance.OnNavigateArrowRight;
            @NavigateArrowRight.performed -= instance.OnNavigateArrowRight;
            @NavigateArrowRight.canceled -= instance.OnNavigateArrowRight;
            @OpenCloseCraftingMenu.started -= instance.OnOpenCloseCraftingMenu;
            @OpenCloseCraftingMenu.performed -= instance.OnOpenCloseCraftingMenu;
            @OpenCloseCraftingMenu.canceled -= instance.OnOpenCloseCraftingMenu;
            @OpenCloseEquipmentAndFood.started -= instance.OnOpenCloseEquipmentAndFood;
            @OpenCloseEquipmentAndFood.performed -= instance.OnOpenCloseEquipmentAndFood;
            @OpenCloseEquipmentAndFood.canceled -= instance.OnOpenCloseEquipmentAndFood;
            @Craft.started -= instance.OnCraft;
            @Craft.performed -= instance.OnCraft;
            @Craft.canceled -= instance.OnCraft;
            @ConfirmPlacement.started -= instance.OnConfirmPlacement;
            @ConfirmPlacement.performed -= instance.OnConfirmPlacement;
            @ConfirmPlacement.canceled -= instance.OnConfirmPlacement;
            @CancelPlacement.started -= instance.OnCancelPlacement;
            @CancelPlacement.performed -= instance.OnCancelPlacement;
            @CancelPlacement.canceled -= instance.OnCancelPlacement;
            @ShowHideDebugTools.started -= instance.OnShowHideDebugTools;
            @ShowHideDebugTools.performed -= instance.OnShowHideDebugTools;
            @ShowHideDebugTools.canceled -= instance.OnShowHideDebugTools;
            @ReportBug.started -= instance.OnReportBug;
            @ReportBug.performed -= instance.OnReportBug;
            @ReportBug.canceled -= instance.OnReportBug;
        }

        public void RemoveCallbacks(IPlayerActionMapActions instance)
        {
            if (m_Wrapper.m_PlayerActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionMapActions @PlayerActionMap => new PlayerActionMapActions(this);

    // UserIntefaceActionMap
    private readonly InputActionMap m_UserIntefaceActionMap;
    private List<IUserIntefaceActionMapActions> m_UserIntefaceActionMapActionsCallbackInterfaces = new List<IUserIntefaceActionMapActions>();
    private readonly InputAction m_UserIntefaceActionMap_Navigate;
    private readonly InputAction m_UserIntefaceActionMap_Submit;
    private readonly InputAction m_UserIntefaceActionMap_Purge;
    private readonly InputAction m_UserIntefaceActionMap_Reroll;
    private readonly InputAction m_UserIntefaceActionMap_Cancel;
    private readonly InputAction m_UserIntefaceActionMap_Point;
    private readonly InputAction m_UserIntefaceActionMap_Click;
    private readonly InputAction m_UserIntefaceActionMap_ScrollWheel;
    private readonly InputAction m_UserIntefaceActionMap_MiddleClick;
    private readonly InputAction m_UserIntefaceActionMap_RightClick;
    private readonly InputAction m_UserIntefaceActionMap_Esc;
    private readonly InputAction m_UserIntefaceActionMap_TrackedDevicePosition;
    private readonly InputAction m_UserIntefaceActionMap_TrackedDeviceOrientation;
    private readonly InputAction m_UserIntefaceActionMap_Start;
    private readonly InputAction m_UserIntefaceActionMap_Console;
    public struct UserIntefaceActionMapActions
    {
        private @MyInputActions m_Wrapper;
        public UserIntefaceActionMapActions(@MyInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UserIntefaceActionMap_Navigate;
        public InputAction @Submit => m_Wrapper.m_UserIntefaceActionMap_Submit;
        public InputAction @Purge => m_Wrapper.m_UserIntefaceActionMap_Purge;
        public InputAction @Reroll => m_Wrapper.m_UserIntefaceActionMap_Reroll;
        public InputAction @Cancel => m_Wrapper.m_UserIntefaceActionMap_Cancel;
        public InputAction @Point => m_Wrapper.m_UserIntefaceActionMap_Point;
        public InputAction @Click => m_Wrapper.m_UserIntefaceActionMap_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UserIntefaceActionMap_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UserIntefaceActionMap_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UserIntefaceActionMap_RightClick;
        public InputAction @Esc => m_Wrapper.m_UserIntefaceActionMap_Esc;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_UserIntefaceActionMap_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UserIntefaceActionMap_TrackedDeviceOrientation;
        public InputAction @Start => m_Wrapper.m_UserIntefaceActionMap_Start;
        public InputAction @Console => m_Wrapper.m_UserIntefaceActionMap_Console;
        public InputActionMap Get() { return m_Wrapper.m_UserIntefaceActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UserIntefaceActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IUserIntefaceActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_UserIntefaceActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UserIntefaceActionMapActionsCallbackInterfaces.Add(instance);
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Purge.started += instance.OnPurge;
            @Purge.performed += instance.OnPurge;
            @Purge.canceled += instance.OnPurge;
            @Reroll.started += instance.OnReroll;
            @Reroll.performed += instance.OnReroll;
            @Reroll.canceled += instance.OnReroll;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Point.started += instance.OnPoint;
            @Point.performed += instance.OnPoint;
            @Point.canceled += instance.OnPoint;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @ScrollWheel.started += instance.OnScrollWheel;
            @ScrollWheel.performed += instance.OnScrollWheel;
            @ScrollWheel.canceled += instance.OnScrollWheel;
            @MiddleClick.started += instance.OnMiddleClick;
            @MiddleClick.performed += instance.OnMiddleClick;
            @MiddleClick.canceled += instance.OnMiddleClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @Esc.started += instance.OnEsc;
            @Esc.performed += instance.OnEsc;
            @Esc.canceled += instance.OnEsc;
            @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
            @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
            @Console.started += instance.OnConsole;
            @Console.performed += instance.OnConsole;
            @Console.canceled += instance.OnConsole;
        }

        private void UnregisterCallbacks(IUserIntefaceActionMapActions instance)
        {
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Purge.started -= instance.OnPurge;
            @Purge.performed -= instance.OnPurge;
            @Purge.canceled -= instance.OnPurge;
            @Reroll.started -= instance.OnReroll;
            @Reroll.performed -= instance.OnReroll;
            @Reroll.canceled -= instance.OnReroll;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Point.started -= instance.OnPoint;
            @Point.performed -= instance.OnPoint;
            @Point.canceled -= instance.OnPoint;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @ScrollWheel.started -= instance.OnScrollWheel;
            @ScrollWheel.performed -= instance.OnScrollWheel;
            @ScrollWheel.canceled -= instance.OnScrollWheel;
            @MiddleClick.started -= instance.OnMiddleClick;
            @MiddleClick.performed -= instance.OnMiddleClick;
            @MiddleClick.canceled -= instance.OnMiddleClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @Esc.started -= instance.OnEsc;
            @Esc.performed -= instance.OnEsc;
            @Esc.canceled -= instance.OnEsc;
            @TrackedDevicePosition.started -= instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.performed -= instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.canceled -= instance.OnTrackedDevicePosition;
            @TrackedDeviceOrientation.started -= instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.performed -= instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.canceled -= instance.OnTrackedDeviceOrientation;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
            @Console.started -= instance.OnConsole;
            @Console.performed -= instance.OnConsole;
            @Console.canceled -= instance.OnConsole;
        }

        public void RemoveCallbacks(IUserIntefaceActionMapActions instance)
        {
            if (m_Wrapper.m_UserIntefaceActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUserIntefaceActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_UserIntefaceActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UserIntefaceActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UserIntefaceActionMapActions @UserIntefaceActionMap => new UserIntefaceActionMapActions(this);

    // CraftingBookActionMap
    private readonly InputActionMap m_CraftingBookActionMap;
    private List<ICraftingBookActionMapActions> m_CraftingBookActionMapActionsCallbackInterfaces = new List<ICraftingBookActionMapActions>();
    private readonly InputAction m_CraftingBookActionMap_Navigate;
    public struct CraftingBookActionMapActions
    {
        private @MyInputActions m_Wrapper;
        public CraftingBookActionMapActions(@MyInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_CraftingBookActionMap_Navigate;
        public InputActionMap Get() { return m_Wrapper.m_CraftingBookActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CraftingBookActionMapActions set) { return set.Get(); }
        public void AddCallbacks(ICraftingBookActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_CraftingBookActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CraftingBookActionMapActionsCallbackInterfaces.Add(instance);
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
        }

        private void UnregisterCallbacks(ICraftingBookActionMapActions instance)
        {
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
        }

        public void RemoveCallbacks(ICraftingBookActionMapActions instance)
        {
            if (m_Wrapper.m_CraftingBookActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICraftingBookActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_CraftingBookActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CraftingBookActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CraftingBookActionMapActions @CraftingBookActionMap => new CraftingBookActionMapActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActionMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnAimAndFire(InputAction.CallbackContext context);
        void OnFire1(InputAction.CallbackContext context);
        void OnFire2(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
        void OnNumkeys(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnNavigateLeft(InputAction.CallbackContext context);
        void OnNavigateRight(InputAction.CallbackContext context);
        void OnNavigateArrowLeft(InputAction.CallbackContext context);
        void OnNavigateArrowRight(InputAction.CallbackContext context);
        void OnOpenCloseCraftingMenu(InputAction.CallbackContext context);
        void OnOpenCloseEquipmentAndFood(InputAction.CallbackContext context);
        void OnCraft(InputAction.CallbackContext context);
        void OnConfirmPlacement(InputAction.CallbackContext context);
        void OnCancelPlacement(InputAction.CallbackContext context);
        void OnShowHideDebugTools(InputAction.CallbackContext context);
        void OnReportBug(InputAction.CallbackContext context);
    }
    public interface IUserIntefaceActionMapActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnPurge(InputAction.CallbackContext context);
        void OnReroll(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnConsole(InputAction.CallbackContext context);
    }
    public interface ICraftingBookActionMapActions
    {
        void OnNavigate(InputAction.CallbackContext context);
    }
}
